# Generated by Django 5.1.5 on 2025-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ragister',
            fields=[
                ('srno', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('conpassword', models.CharField(max_length=20)),
            ],
        ),
    ]
