# Generated by Django 5.1.5 on 2025-04-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0002_ragister'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='conpassword',
        ),
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
        migrations.AlterField(
            model_name='login',
            name='email_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ragister',
            name='email_id',
            field=models.CharField(max_length=40),
        ),
    ]
