# Generated by Django 5.1.4 on 2025-04-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0003_remove_login_conpassword_remove_login_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('User_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Full_Name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=30)),
                ('Mobie_number', models.CharField(max_length=15)),
                ('Adhar_card', models.CharField(max_length=12)),
                ('date_arrivale', models.CharField(max_length=30)),
                ('date_return', models.CharField(max_length=30)),
                ('adults_kids', models.CharField(max_length=10)),
                ('Room_type', models.CharField(max_length=30)),
                ('Special_Requests', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('Rating_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('package_id', models.IntegerField(unique=True)),
                ('rating', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='package',
            fields=[
                ('package_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('place_image', models.CharField(max_length=40)),
                ('place_name', models.CharField(max_length=40)),
                ('package_price', models.IntegerField()),
                ('package_detail', models.CharField(max_length=40)),
                ('image_gallary', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(unique=True)),
                ('package_id', models.IntegerField(unique=True)),
                ('payment_type', models.CharField(max_length=50)),
            ],
        ),
    ]
