# Generated by Django 5.1.4 on 2025-04-22 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0004_booking_feedback_package_payment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='user_login',
        ),
    ]
