# Generated by Django 5.1.4 on 2025-04-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0005_rename_login_user_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='package_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
