# Generated by Django 5.1.4 on 2025-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0006_package_package_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_desc',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
