# Generated by Django 5.1.4 on 2025-04-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0007_alter_package_package_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attractions',
            fields=[
                ('att_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('att_name', models.CharField(max_length=40)),
                ('att_image', models.CharField(max_length=40)),
                ('att_desc', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
