# Generated by Django 5.1.4 on 2025-04-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0008_attractions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attractions',
            name='att_image',
            field=models.CharField(max_length=80),
        ),
    ]
