# Generated by Django 5.1.4 on 2025-04-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0009_alter_attractions_att_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attractions',
            name='place_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
