# Generated by Django 5.1.4 on 2025-04-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0010_attractions_place_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Full_Name',
            new_name='place_Name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
    ]
