# Generated by Django 5.1.4 on 2025-04-23 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0011_rename_full_name_booking_place_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='place_Name',
            new_name='place_name',
        ),
    ]
