# Generated by Django 5.1.4 on 2025-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0012_rename_place_name_booking_place_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
