# Generated by Django 5.1.4 on 2025-04-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0015_alter_booking_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='package_id',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='user_id',
        ),
        migrations.AddField(
            model_name='feedback',
            name='package_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='discription',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(max_length=5, null=True),
        ),
    ]
