# Generated by Django 5.1.4 on 2025-04-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0016_remove_feedback_package_id_remove_feedback_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
