# Generated by Django 5.1.4 on 2025-04-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0017_alter_feedback_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
