# Generated by Django 5.1.4 on 2025-04-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0018_booking_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='place_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user_name',
            field=models.CharField(max_length=30),
        ),
    ]
