# Generated by Django 5.1.4 on 2025-04-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0019_alter_booking_place_name_alter_booking_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
