# Generated by Django 5.1.4 on 2025-04-24 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0021_alter_payment_amount_alter_payment_package_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='package_detail',
            new_name='package_name',
        ),
    ]
