# Generated by Django 5.1.4 on 2025-04-25 08:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0022_rename_package_detail_package_package_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ragister',
            old_name='srno',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='ragister',
            name='join_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
