# Generated by Django 5.1.4 on 2025-04-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0023_rename_srno_ragister_user_id_ragister_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
