# Generated by Django 5.1.4 on 2025-04-25 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0026_feedback_r_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='r_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
