# Generated by Django 5.1.4 on 2025-04-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0028_alter_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.IntegerField(default=1500),
        ),
    ]
