# Generated by Django 5.1.4 on 2025-04-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0033_alter_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
