# Generated by Django 5.1.4 on 2025-04-25 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0034_feedback_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('hotel_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=40, null=True)),
                ('hotel_loc', models.CharField(max_length=40, null=True)),
                ('hotel_price', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
