# Generated by Django 5.1.4 on 2025-04-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0035_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ragister',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='img/'),
            preserve_default=False,
        ),
    ]
