# Generated by Django 5.1.4 on 2025-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0036_ragister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragister',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
