# Generated by Django 5.1.4 on 2025-04-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0037_alter_ragister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragister',
            name='image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
