# Generated by Django 5.1.4 on 2025-04-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0038_alter_ragister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ragister',
            name='image',
            field=models.CharField(default='/tour_and_travalling/static/img/profile.jpg', max_length=100, null=True),
        ),
    ]
