# Generated by Django 5.1.4 on 2025-04-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0039_alter_ragister_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='image_gallary',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='place_image',
            field=models.ImageField(upload_to='places/'),
        ),
    ]
