# Generated by Django 5.1.5 on 2025-05-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_and_travalling', '0040_alter_package_image_gallary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='image',
            field=models.ImageField(default='profile.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='ragister',
            name='image',
            field=models.ImageField(default='profile.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
